name: gaussian_splatting
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.7
  - plyfile
  - python=3.9.16
  - pip=23.0.1
  - pytorch=2.0.1
  - torchvision=0.15.2
  - tqdm
